apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate a ConfigMap based on the environment variables in the file `.env`.
configMapGenerator:
  - name: deployments-config-map
    envs: 
      - .env.production

replacements:
  - source:
      # Replace any matches by the value of environment variable `MY_IMAGE_TAG`.
      kind: ConfigMap
      name: deployments-config-map
      fieldPath: data.APP_VERSION
    targets:
      - select:
          # In each Deployment resource …
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=application].image
        options:
          # … but replace only the second part (image tag) when split by ":".
          delimiter: ":"
          index: 1

resources:
  - app/1_common/config-map.yml
  - app/2_application/deployment.yml
