apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: nuxt-in-kubernetes-application
spec:
  selector:
    tier: backend
    layer: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000